version: '3.2'

services:
    redis:
        image: redis:5.0-alpine
        ports:
            - 6379:6379

    mysql:
        image: mysql:8
        volumes:
            # - ./public/db/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: saboroso
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306

volumes:
    mysql-data: